# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Crossing the Aisle
tagline:             'Talking to Conservatives'
description:         "2016 revealed a gaping hole in US discourse: Americans have lost the ability to talk to people outside our political tribes.  We are fixing that."
url:                 http://trumptalks.herokuapp.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ben W
  url:
  email:

# Custom vars
version:             1.0.0
gems:             [jekyll-paginate]
